version: '3'

services:
  app:
    image: 'primer-api:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/primer-api
      - SPRING_DATASOURCE_USERNAME=primer-api
      - SPRING_DATASOURCE_PASSWORD=primer-api
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 9000:8090
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=primer-api
      - POSTGRES_PASSWORD=primer-api